// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/db/entities/biomarker_record_ob.dart';
import 'core/db/entities/config_ob.dart';
import 'core/db/entities/dexa_scan_ob.dart';
import 'core/db/entities/gut_health_item_ob.dart';
import 'core/db/entities/habit_log_ob.dart';
import 'core/db/entities/habit_ob.dart';
import 'core/db/entities/intake_ob.dart';
import 'core/db/entities/physical_activity_ob.dart';
import 'core/db/entities/stool_log_ob.dart';
import 'core/db/entities/symptom_log_ob.dart';
import 'core/db/entities/tracked_day_ob.dart';
import 'core/db/entities/user_activity_ob.dart';
import 'core/db/entities/user_ob.dart';
import 'core/db/entities/water_record_ob.dart';
import 'core/db/entities/weight_record_ob.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6477492202799954719),
    name: 'ConfigOB',
    lastPropertyId: const obx_int.IdUid(12, 1159123641096979405),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7096599062265612196),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1605258323807072596),
        name: 'hasAcceptedDisclaimer',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8103748892177643272),
        name: 'hasAcceptedPolicy',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 535698736857720524),
        name: 'hasAcceptedSendAnonymousData',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5673420628141000510),
        name: 'selectedAppTheme',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4099500244323632474),
        name: 'usesImperialUnits',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4948167303530435595),
        name: 'userKcalAdjustment',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7546070661011258207),
        name: 'userCarbGoalPct',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 515557426401210509),
        name: 'userProteinGoalPct',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 703665110577707782),
        name: 'userFatGoalPct',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1547450199447428793),
        name: 'hiveMigrationComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1159123641096979405),
        name: 'targetWeightKG',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 222820024314402058),
    name: 'IntakeOB',
    lastPropertyId: const obx_int.IdUid(51, 2380785250413604025),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 520811337062894370),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5059740210341806401),
        name: 'intakeId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6349337231928206960),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8953215190018559102),
        name: 'unit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1259916367482994431),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1423991108552084467),
        name: 'intakeType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1145201112684106461),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 936581049233374452),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1003025297402387938),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5573768768984622890),
        name: 'brands',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1543503185922050525),
        name: 'thumbnailImageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1040625899674691151),
        name: 'mainImageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5732902005959526953),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6112917965149515132),
        name: 'mealQuantity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6483345057335549356),
        name: 'mealUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5424539592310399042),
        name: 'servingQuantity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 9019034584142787756),
        name: 'servingUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3857457929341562138),
        name: 'servingSize',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 4990414656831801035),
        name: 'mealSource',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 7675916854437309933),
        name: 'energyKcal100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 2035247653380367410),
        name: 'carbohydrates100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 607795541679044784),
        name: 'fat100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 658156367839574930),
        name: 'proteins100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 3607472227833157161),
        name: 'sugars100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 7388097191242464657),
        name: 'saturatedFat100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 3331335119793687726),
        name: 'fiber100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 2751917060317918041),
        name: 'sodium100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 6106563860771147160),
        name: 'potassium100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 3983056364114996429),
        name: 'calcium100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 6375128194613779203),
        name: 'iron100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 6358235870478816759),
        name: 'magnesium100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 5080574838137777033),
        name: 'phosphorus100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 3253887370971635581),
        name: 'zinc100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 2477986222544339043),
        name: 'copper100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 4597288143175488768),
        name: 'manganese100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 2684091126884698254),
        name: 'selenium100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 4435583683495340630),
        name: 'vitaminA100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 2002082733397751101),
        name: 'vitaminC100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 7886685951497628931),
        name: 'vitaminD100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 6147560639452323478),
        name: 'vitaminE100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(40, 6749101435642143216),
        name: 'vitaminK100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(41, 8276312380632166752),
        name: 'thiamine100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 8641832840537544956),
        name: 'riboflavin100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(43, 6898223419118814140),
        name: 'niacin100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(44, 3268045021358642101),
        name: 'pantothenicAcid100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(45, 8995285452069790636),
        name: 'vitaminB6100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(46, 3447893195242372239),
        name: 'folate100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(47, 2201541038774179969),
        name: 'vitaminB12100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(48, 3176894868595651877),
        name: 'cholesterol100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(49, 8262917921999380575),
        name: 'addedSugars100',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(50, 7470205969616379032),
        name: 'additivesTags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(51, 2380785250413604025),
        name: 'ingredientsText',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2952592799405788095),
    name: 'PhysicalActivityOB',
    lastPropertyId: const obx_int.IdUid(7, 8034931056275971149),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4945908154863518828),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7480938192033899768),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1828750019567401219),
        name: 'specificActivity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2333513107317218138),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6225554774266298739),
        name: 'mets',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2383359518533308175),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8034931056275971149),
        name: 'activityType',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3950974448860086310),
    name: 'TrackedDayOB',
    lastPropertyId: const obx_int.IdUid(10, 2683328908506704349),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2545928256364671177),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1661301873262312958),
        name: 'day',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6407337014019156484),
        name: 'calorieGoal',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6084963763959822724),
        name: 'caloriesTracked',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5447489510314645824),
        name: 'carbsGoal',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1138120974796152942),
        name: 'carbsTracked',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3791164846714037286),
        name: 'fatGoal',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2170125685297133417),
        name: 'fatTracked',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3040539820399501461),
        name: 'proteinGoal',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2683328908506704349),
        name: 'proteinTracked',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 9089101762990167869),
    name: 'UserActivityOB',
    lastPropertyId: const obx_int.IdUid(11, 7202365980286144645),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 505450033182266586),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5549108869722236220),
        name: 'activityId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7319863865959781371),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8054229638233298773),
        name: 'duration',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1731960800043902334),
        name: 'burnedKcal',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6475511088355020178),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 157102528658202797),
        name: 'activityCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4148409488685750977),
        name: 'specificActivity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7788434800093330013),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9220718011580399226),
        name: 'mets',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5341352563548111910),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7202365980286144645),
        name: 'activityType',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7636978955874029769),
    name: 'UserOB',
    lastPropertyId: const obx_int.IdUid(7, 7685946749923979441),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5435496905879134844),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3812970747142964100),
        name: 'birthday',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7923550915521047736),
        name: 'heightCM',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4174754889585241468),
        name: 'weightKG',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1759332707758468134),
        name: 'gender',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4457269851161958463),
        name: 'goal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7685946749923979441),
        name: 'pal',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2494492286301300394),
    name: 'GutHealthItemOB',
    lastPropertyId: const obx_int.IdUid(6, 3486255085334882947),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7811082825313000450),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7887262344800656475),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2899736536307687814),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8816371267439659764),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6793353370448096568),
        name: 'isAutoFlagged',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3486255085334882947),
        name: 'sourceIntakeId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 1370534373946555578),
    name: 'HabitLogOB',
    lastPropertyId: const obx_int.IdUid(4, 5571970018044348505),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7979968088678243758),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7061718633088095527),
        name: 'habitId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5080065482921261631),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5571970018044348505),
        name: 'completed',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 3446880705750154736),
    name: 'HabitOB',
    lastPropertyId: const obx_int.IdUid(5, 3267316403142564014),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6923817044308253331),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6152132543417919542),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5156324938121614033),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1395827786658467559),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3267316403142564014),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 789815896546770560),
    name: 'WaterRecordOB',
    lastPropertyId: const obx_int.IdUid(3, 6686232328674370670),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 218454635503609085),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 347473416817126082),
        name: 'amountML',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6686232328674370670),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 5538860049560825163),
    name: 'WeightRecordOB',
    lastPropertyId: const obx_int.IdUid(3, 896787463902377656),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4429405453386792156),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6705470113916040982),
        name: 'weightKG',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 896787463902377656),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 4420710930980106944),
    name: 'StoolLogOB',
    lastPropertyId: const obx_int.IdUid(4, 1183281187575080314),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8278386601570190806),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1440122297551028151),
        name: 'type',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6471414013196193241),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1183281187575080314),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 982607073446383719),
    name: 'SymptomLogOB',
    lastPropertyId: const obx_int.IdUid(5, 9008183605618040204),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3152687350290846821),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7228128909076205063),
        name: 'symptom',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4378226166795625323),
        name: 'severity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 821579706350880651),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9008183605618040204),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(14, 1034035110825751383),
    name: 'BiomarkerRecordOB',
    lastPropertyId: const obx_int.IdUid(6, 4387178617261170057),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6763726702024422674),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2493638220060392753),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1535579681657601768),
        name: 'value',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6100382431439389365),
        name: 'unit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8837958407090471998),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4387178617261170057),
        name: 'source',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(15, 1781774396636105369),
    name: 'DexaScanOB',
    lastPropertyId: const obx_int.IdUid(8, 1182332487767697968),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3033203686372988373),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3980876848470724272),
        name: 'scanDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 896041955866674216),
        name: 'totalBodyFatPercent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8090251611330965577),
        name: 'leanMassKG',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1115534957770209102),
        name: 'fatMassKG',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 884374273444776209),
        name: 'boneMineralDensity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2121348649363414868),
        name: 'visceralFatArea',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1182332487767697968),
        name: 'tScore',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(15, 1781774396636105369),
    lastIndexId: const obx_int.IdUid(2, 7319863865959781371),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ConfigOB: obx_int.EntityDefinition<ConfigOB>(
      model: _entities[0],
      toOneRelations: (ConfigOB object) => [],
      toManyRelations: (ConfigOB object) => {},
      getId: (ConfigOB object) => object.id,
      setId: (ConfigOB object, int id) {
        object.id = id;
      },
      objectToFB: (ConfigOB object, fb.Builder fbb) {
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.hasAcceptedDisclaimer);
        fbb.addBool(2, object.hasAcceptedPolicy);
        fbb.addBool(3, object.hasAcceptedSendAnonymousData);
        fbb.addInt64(4, object.selectedAppTheme);
        fbb.addBool(5, object.usesImperialUnits);
        fbb.addFloat64(6, object.userKcalAdjustment);
        fbb.addFloat64(7, object.userCarbGoalPct);
        fbb.addFloat64(8, object.userProteinGoalPct);
        fbb.addFloat64(9, object.userFatGoalPct);
        fbb.addBool(10, object.hiveMigrationComplete);
        fbb.addFloat64(11, object.targetWeightKG);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final hasAcceptedDisclaimerParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final hasAcceptedPolicyParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final hasAcceptedSendAnonymousDataParam = const fb.BoolReader()
            .vTableGet(buffer, rootOffset, 10, false);
        final selectedAppThemeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final usesImperialUnitsParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final userKcalAdjustmentParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final userCarbGoalPctParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final userProteinGoalPctParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 20);
        final userFatGoalPctParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final hiveMigrationCompleteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final targetWeightKGParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final object = ConfigOB(
          id: idParam,
          hasAcceptedDisclaimer: hasAcceptedDisclaimerParam,
          hasAcceptedPolicy: hasAcceptedPolicyParam,
          hasAcceptedSendAnonymousData: hasAcceptedSendAnonymousDataParam,
          selectedAppTheme: selectedAppThemeParam,
          usesImperialUnits: usesImperialUnitsParam,
          userKcalAdjustment: userKcalAdjustmentParam,
          userCarbGoalPct: userCarbGoalPctParam,
          userProteinGoalPct: userProteinGoalPctParam,
          userFatGoalPct: userFatGoalPctParam,
          hiveMigrationComplete: hiveMigrationCompleteParam,
          targetWeightKG: targetWeightKGParam,
        );

        return object;
      },
    ),
    IntakeOB: obx_int.EntityDefinition<IntakeOB>(
      model: _entities[1],
      toOneRelations: (IntakeOB object) => [],
      toManyRelations: (IntakeOB object) => {},
      getId: (IntakeOB object) => object.id,
      setId: (IntakeOB object, int id) {
        object.id = id;
      },
      objectToFB: (IntakeOB object, fb.Builder fbb) {
        final intakeIdOffset = fbb.writeString(object.intakeId);
        final unitOffset = fbb.writeString(object.unit);
        final codeOffset = object.code == null
            ? null
            : fbb.writeString(object.code!);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final brandsOffset = object.brands == null
            ? null
            : fbb.writeString(object.brands!);
        final thumbnailImageUrlOffset = object.thumbnailImageUrl == null
            ? null
            : fbb.writeString(object.thumbnailImageUrl!);
        final mainImageUrlOffset = object.mainImageUrl == null
            ? null
            : fbb.writeString(object.mainImageUrl!);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final mealQuantityOffset = object.mealQuantity == null
            ? null
            : fbb.writeString(object.mealQuantity!);
        final mealUnitOffset = object.mealUnit == null
            ? null
            : fbb.writeString(object.mealUnit!);
        final servingUnitOffset = object.servingUnit == null
            ? null
            : fbb.writeString(object.servingUnit!);
        final servingSizeOffset = object.servingSize == null
            ? null
            : fbb.writeString(object.servingSize!);
        final additivesTagsOffset = object.additivesTags == null
            ? null
            : fbb.writeList(
                object.additivesTags!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final ingredientsTextOffset = object.ingredientsText == null
            ? null
            : fbb.writeString(object.ingredientsText!);
        fbb.startTable(52);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, intakeIdOffset);
        fbb.addOffset(2, unitOffset);
        fbb.addFloat64(3, object.amount);
        fbb.addInt64(4, object.intakeType);
        fbb.addInt64(5, object.dateTime.millisecondsSinceEpoch);
        fbb.addOffset(6, codeOffset);
        fbb.addOffset(7, nameOffset);
        fbb.addOffset(8, brandsOffset);
        fbb.addOffset(9, thumbnailImageUrlOffset);
        fbb.addOffset(10, mainImageUrlOffset);
        fbb.addOffset(11, urlOffset);
        fbb.addOffset(12, mealQuantityOffset);
        fbb.addOffset(13, mealUnitOffset);
        fbb.addFloat64(14, object.servingQuantity);
        fbb.addOffset(15, servingUnitOffset);
        fbb.addOffset(16, servingSizeOffset);
        fbb.addInt64(17, object.mealSource);
        fbb.addFloat64(18, object.energyKcal100);
        fbb.addFloat64(19, object.carbohydrates100);
        fbb.addFloat64(20, object.fat100);
        fbb.addFloat64(21, object.proteins100);
        fbb.addFloat64(22, object.sugars100);
        fbb.addFloat64(23, object.saturatedFat100);
        fbb.addFloat64(24, object.fiber100);
        fbb.addFloat64(25, object.sodium100);
        fbb.addFloat64(26, object.potassium100);
        fbb.addFloat64(27, object.calcium100);
        fbb.addFloat64(28, object.iron100);
        fbb.addFloat64(29, object.magnesium100);
        fbb.addFloat64(30, object.phosphorus100);
        fbb.addFloat64(31, object.zinc100);
        fbb.addFloat64(32, object.copper100);
        fbb.addFloat64(33, object.manganese100);
        fbb.addFloat64(34, object.selenium100);
        fbb.addFloat64(35, object.vitaminA100);
        fbb.addFloat64(36, object.vitaminC100);
        fbb.addFloat64(37, object.vitaminD100);
        fbb.addFloat64(38, object.vitaminE100);
        fbb.addFloat64(39, object.vitaminK100);
        fbb.addFloat64(40, object.thiamine100);
        fbb.addFloat64(41, object.riboflavin100);
        fbb.addFloat64(42, object.niacin100);
        fbb.addFloat64(43, object.pantothenicAcid100);
        fbb.addFloat64(44, object.vitaminB6100);
        fbb.addFloat64(45, object.folate100);
        fbb.addFloat64(46, object.vitaminB12100);
        fbb.addFloat64(47, object.cholesterol100);
        fbb.addFloat64(48, object.addedSugars100);
        fbb.addOffset(49, additivesTagsOffset);
        fbb.addOffset(50, ingredientsTextOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final intakeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final unitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final intakeTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final brandsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final thumbnailImageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final mainImageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final mealQuantityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final mealUnitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final servingQuantityParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final servingUnitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final servingSizeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final mealSourceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final energyKcal100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          40,
        );
        final carbohydrates100Param = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 42);
        final fat100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          44,
        );
        final proteins100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          46,
        );
        final sugars100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          48,
        );
        final saturatedFat100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          50,
        );
        final fiber100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          52,
        );
        final sodium100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final potassium100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          56,
        );
        final calcium100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          58,
        );
        final iron100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          60,
        );
        final magnesium100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          62,
        );
        final phosphorus100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          64,
        );
        final zinc100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          66,
        );
        final copper100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          68,
        );
        final manganese100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          70,
        );
        final selenium100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          72,
        );
        final vitaminA100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          74,
        );
        final vitaminC100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          76,
        );
        final vitaminD100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          78,
        );
        final vitaminE100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          80,
        );
        final vitaminK100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          82,
        );
        final thiamine100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          84,
        );
        final riboflavin100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          86,
        );
        final niacin100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          88,
        );
        final pantothenicAcid100Param = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 90);
        final vitaminB6100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          92,
        );
        final folate100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          94,
        );
        final vitaminB12100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          96,
        );
        final cholesterol100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          98,
        );
        final addedSugars100Param = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          100,
        );
        final additivesTagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 102);
        final ingredientsTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 104);
        final object = IntakeOB(
          id: idParam,
          intakeId: intakeIdParam,
          unit: unitParam,
          amount: amountParam,
          intakeType: intakeTypeParam,
          dateTime: dateTimeParam,
          code: codeParam,
          name: nameParam,
          brands: brandsParam,
          thumbnailImageUrl: thumbnailImageUrlParam,
          mainImageUrl: mainImageUrlParam,
          url: urlParam,
          mealQuantity: mealQuantityParam,
          mealUnit: mealUnitParam,
          servingQuantity: servingQuantityParam,
          servingUnit: servingUnitParam,
          servingSize: servingSizeParam,
          mealSource: mealSourceParam,
          energyKcal100: energyKcal100Param,
          carbohydrates100: carbohydrates100Param,
          fat100: fat100Param,
          proteins100: proteins100Param,
          sugars100: sugars100Param,
          saturatedFat100: saturatedFat100Param,
          fiber100: fiber100Param,
          sodium100: sodium100Param,
          potassium100: potassium100Param,
          calcium100: calcium100Param,
          iron100: iron100Param,
          magnesium100: magnesium100Param,
          phosphorus100: phosphorus100Param,
          zinc100: zinc100Param,
          copper100: copper100Param,
          manganese100: manganese100Param,
          selenium100: selenium100Param,
          vitaminA100: vitaminA100Param,
          vitaminC100: vitaminC100Param,
          vitaminD100: vitaminD100Param,
          vitaminE100: vitaminE100Param,
          vitaminK100: vitaminK100Param,
          thiamine100: thiamine100Param,
          riboflavin100: riboflavin100Param,
          niacin100: niacin100Param,
          pantothenicAcid100: pantothenicAcid100Param,
          vitaminB6100: vitaminB6100Param,
          folate100: folate100Param,
          vitaminB12100: vitaminB12100Param,
          cholesterol100: cholesterol100Param,
          addedSugars100: addedSugars100Param,
          additivesTags: additivesTagsParam,
          ingredientsText: ingredientsTextParam,
        );

        return object;
      },
    ),
    PhysicalActivityOB: obx_int.EntityDefinition<PhysicalActivityOB>(
      model: _entities[2],
      toOneRelations: (PhysicalActivityOB object) => [],
      toManyRelations: (PhysicalActivityOB object) => {},
      getId: (PhysicalActivityOB object) => object.id,
      setId: (PhysicalActivityOB object, int id) {
        object.id = id;
      },
      objectToFB: (PhysicalActivityOB object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final specificActivityOffset = fbb.writeString(object.specificActivity);
        final descriptionOffset = fbb.writeString(object.description);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, specificActivityOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addFloat64(4, object.mets);
        fbb.addOffset(5, tagsOffset);
        fbb.addInt64(6, object.activityType);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final specificActivityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final metsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final activityTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = PhysicalActivityOB(
          id: idParam,
          code: codeParam,
          specificActivity: specificActivityParam,
          description: descriptionParam,
          mets: metsParam,
          tags: tagsParam,
          activityType: activityTypeParam,
        );

        return object;
      },
    ),
    TrackedDayOB: obx_int.EntityDefinition<TrackedDayOB>(
      model: _entities[3],
      toOneRelations: (TrackedDayOB object) => [],
      toManyRelations: (TrackedDayOB object) => {},
      getId: (TrackedDayOB object) => object.id,
      setId: (TrackedDayOB object, int id) {
        object.id = id;
      },
      objectToFB: (TrackedDayOB object, fb.Builder fbb) {
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.day.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.calorieGoal);
        fbb.addFloat64(3, object.caloriesTracked);
        fbb.addFloat64(4, object.carbsGoal);
        fbb.addFloat64(5, object.carbsTracked);
        fbb.addFloat64(6, object.fatGoal);
        fbb.addFloat64(7, object.fatTracked);
        fbb.addFloat64(8, object.proteinGoal);
        fbb.addFloat64(9, object.proteinTracked);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dayParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final calorieGoalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final caloriesTrackedParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final carbsGoalParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final carbsTrackedParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final fatGoalParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final fatTrackedParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final proteinGoalParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final proteinTrackedParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final object = TrackedDayOB(
          id: idParam,
          day: dayParam,
          calorieGoal: calorieGoalParam,
          caloriesTracked: caloriesTrackedParam,
          carbsGoal: carbsGoalParam,
          carbsTracked: carbsTrackedParam,
          fatGoal: fatGoalParam,
          fatTracked: fatTrackedParam,
          proteinGoal: proteinGoalParam,
          proteinTracked: proteinTrackedParam,
        );

        return object;
      },
    ),
    UserActivityOB: obx_int.EntityDefinition<UserActivityOB>(
      model: _entities[4],
      toOneRelations: (UserActivityOB object) => [],
      toManyRelations: (UserActivityOB object) => {},
      getId: (UserActivityOB object) => object.id,
      setId: (UserActivityOB object, int id) {
        object.id = id;
      },
      objectToFB: (UserActivityOB object, fb.Builder fbb) {
        final activityIdOffset = fbb.writeString(object.activityId);
        final activityCodeOffset = fbb.writeString(object.activityCode);
        final specificActivityOffset = fbb.writeString(object.specificActivity);
        final descriptionOffset = fbb.writeString(object.description);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, activityIdOffset);
        fbb.addFloat64(2, object.duration);
        fbb.addFloat64(3, object.burnedKcal);
        fbb.addInt64(4, object.date.millisecondsSinceEpoch);
        fbb.addOffset(5, activityCodeOffset);
        fbb.addOffset(6, specificActivityOffset);
        fbb.addOffset(7, descriptionOffset);
        fbb.addFloat64(8, object.mets);
        fbb.addOffset(9, tagsOffset);
        fbb.addInt64(10, object.activityType);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final activityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final durationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final burnedKcalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final activityCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final specificActivityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final metsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 22, []);
        final activityTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = UserActivityOB(
          id: idParam,
          activityId: activityIdParam,
          duration: durationParam,
          burnedKcal: burnedKcalParam,
          date: dateParam,
          activityCode: activityCodeParam,
          specificActivity: specificActivityParam,
          description: descriptionParam,
          mets: metsParam,
          tags: tagsParam,
          activityType: activityTypeParam,
        );

        return object;
      },
    ),
    UserOB: obx_int.EntityDefinition<UserOB>(
      model: _entities[5],
      toOneRelations: (UserOB object) => [],
      toManyRelations: (UserOB object) => {},
      getId: (UserOB object) => object.id,
      setId: (UserOB object, int id) {
        object.id = id;
      },
      objectToFB: (UserOB object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.birthday.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.heightCM);
        fbb.addFloat64(3, object.weightKG);
        fbb.addInt64(4, object.gender);
        fbb.addInt64(5, object.goal);
        fbb.addInt64(6, object.pal);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final birthdayParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final heightCMParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final weightKGParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final genderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final goalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final palParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = UserOB(
          id: idParam,
          birthday: birthdayParam,
          heightCM: heightCMParam,
          weightKG: weightKGParam,
          gender: genderParam,
          goal: goalParam,
          pal: palParam,
        );

        return object;
      },
    ),
    GutHealthItemOB: obx_int.EntityDefinition<GutHealthItemOB>(
      model: _entities[6],
      toOneRelations: (GutHealthItemOB object) => [],
      toManyRelations: (GutHealthItemOB object) => {},
      getId: (GutHealthItemOB object) => object.id,
      setId: (GutHealthItemOB object, int id) {
        object.id = id;
      },
      objectToFB: (GutHealthItemOB object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final categoryOffset = fbb.writeString(object.category);
        final sourceIntakeIdOffset = object.sourceIntakeId == null
            ? null
            : fbb.writeString(object.sourceIntakeId!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addInt64(3, object.dateTime.millisecondsSinceEpoch);
        fbb.addBool(4, object.isAutoFlagged);
        fbb.addOffset(5, sourceIntakeIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final isAutoFlaggedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final sourceIntakeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = GutHealthItemOB(
          id: idParam,
          name: nameParam,
          category: categoryParam,
          dateTime: dateTimeParam,
          isAutoFlagged: isAutoFlaggedParam,
          sourceIntakeId: sourceIntakeIdParam,
        );

        return object;
      },
    ),
    HabitLogOB: obx_int.EntityDefinition<HabitLogOB>(
      model: _entities[7],
      toOneRelations: (HabitLogOB object) => [],
      toManyRelations: (HabitLogOB object) => {},
      getId: (HabitLogOB object) => object.id,
      setId: (HabitLogOB object, int id) {
        object.id = id;
      },
      objectToFB: (HabitLogOB object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.habitId);
        fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
        fbb.addBool(3, object.completed);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final habitIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final completedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = HabitLogOB(
          id: idParam,
          habitId: habitIdParam,
          dateTime: dateTimeParam,
          completed: completedParam,
        );

        return object;
      },
    ),
    HabitOB: obx_int.EntityDefinition<HabitOB>(
      model: _entities[8],
      toOneRelations: (HabitOB object) => [],
      toManyRelations: (HabitOB object) => {},
      getId: (HabitOB object) => object.id,
      setId: (HabitOB object, int id) {
        object.id = id;
      },
      objectToFB: (HabitOB object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addInt64(3, object.sortOrder);
        fbb.addBool(4, object.isActive);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = HabitOB(
          id: idParam,
          name: nameParam,
          category: categoryParam,
          sortOrder: sortOrderParam,
          isActive: isActiveParam,
        );

        return object;
      },
    ),
    WaterRecordOB: obx_int.EntityDefinition<WaterRecordOB>(
      model: _entities[9],
      toOneRelations: (WaterRecordOB object) => [],
      toManyRelations: (WaterRecordOB object) => {},
      getId: (WaterRecordOB object) => object.id,
      setId: (WaterRecordOB object, int id) {
        object.id = id;
      },
      objectToFB: (WaterRecordOB object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.amountML);
        fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final amountMLParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = WaterRecordOB(
          id: idParam,
          amountML: amountMLParam,
          dateTime: dateTimeParam,
        );

        return object;
      },
    ),
    WeightRecordOB: obx_int.EntityDefinition<WeightRecordOB>(
      model: _entities[10],
      toOneRelations: (WeightRecordOB object) => [],
      toManyRelations: (WeightRecordOB object) => {},
      getId: (WeightRecordOB object) => object.id,
      setId: (WeightRecordOB object, int id) {
        object.id = id;
      },
      objectToFB: (WeightRecordOB object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.weightKG);
        fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final weightKGParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = WeightRecordOB(
          id: idParam,
          weightKG: weightKGParam,
          dateTime: dateTimeParam,
        );

        return object;
      },
    ),
    StoolLogOB: obx_int.EntityDefinition<StoolLogOB>(
      model: _entities[11],
      toOneRelations: (StoolLogOB object) => [],
      toManyRelations: (StoolLogOB object) => {},
      getId: (StoolLogOB object) => object.id,
      setId: (StoolLogOB object, int id) {
        object.id = id;
      },
      objectToFB: (StoolLogOB object, fb.Builder fbb) {
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.type);
        fbb.addInt64(2, object.dateTime.millisecondsSinceEpoch);
        fbb.addOffset(3, notesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = StoolLogOB(
          id: idParam,
          type: typeParam,
          dateTime: dateTimeParam,
          notes: notesParam,
        );

        return object;
      },
    ),
    SymptomLogOB: obx_int.EntityDefinition<SymptomLogOB>(
      model: _entities[12],
      toOneRelations: (SymptomLogOB object) => [],
      toManyRelations: (SymptomLogOB object) => {},
      getId: (SymptomLogOB object) => object.id,
      setId: (SymptomLogOB object, int id) {
        object.id = id;
      },
      objectToFB: (SymptomLogOB object, fb.Builder fbb) {
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.symptom);
        fbb.addInt64(2, object.severity);
        fbb.addInt64(3, object.dateTime.millisecondsSinceEpoch);
        fbb.addOffset(4, notesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final symptomParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final severityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = SymptomLogOB(
          id: idParam,
          symptom: symptomParam,
          severity: severityParam,
          dateTime: dateTimeParam,
          notes: notesParam,
        );

        return object;
      },
    ),
    BiomarkerRecordOB: obx_int.EntityDefinition<BiomarkerRecordOB>(
      model: _entities[13],
      toOneRelations: (BiomarkerRecordOB object) => [],
      toManyRelations: (BiomarkerRecordOB object) => {},
      getId: (BiomarkerRecordOB object) => object.id,
      setId: (BiomarkerRecordOB object, int id) {
        object.id = id;
      },
      objectToFB: (BiomarkerRecordOB object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final unitOffset = fbb.writeString(object.unit);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addFloat64(2, object.value);
        fbb.addOffset(3, unitOffset);
        fbb.addInt64(4, object.dateTime.millisecondsSinceEpoch);
        fbb.addInt64(5, object.source);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final unitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final sourceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = BiomarkerRecordOB(
          id: idParam,
          type: typeParam,
          value: valueParam,
          unit: unitParam,
          dateTime: dateTimeParam,
          source: sourceParam,
        );

        return object;
      },
    ),
    DexaScanOB: obx_int.EntityDefinition<DexaScanOB>(
      model: _entities[14],
      toOneRelations: (DexaScanOB object) => [],
      toManyRelations: (DexaScanOB object) => {},
      getId: (DexaScanOB object) => object.id,
      setId: (DexaScanOB object, int id) {
        object.id = id;
      },
      objectToFB: (DexaScanOB object, fb.Builder fbb) {
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.scanDate.millisecondsSinceEpoch);
        fbb.addFloat64(2, object.totalBodyFatPercent);
        fbb.addFloat64(3, object.leanMassKG);
        fbb.addFloat64(4, object.fatMassKG);
        fbb.addFloat64(5, object.boneMineralDensity);
        fbb.addFloat64(6, object.visceralFatArea);
        fbb.addFloat64(7, object.tScore);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final scanDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final totalBodyFatPercentParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 8);
        final leanMassKGParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final fatMassKGParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final boneMineralDensityParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 14);
        final visceralFatAreaParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final tScoreParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = DexaScanOB(
          id: idParam,
          scanDate: scanDateParam,
          totalBodyFatPercent: totalBodyFatPercentParam,
          leanMassKG: leanMassKGParam,
          fatMassKG: fatMassKGParam,
          boneMineralDensity: boneMineralDensityParam,
          visceralFatArea: visceralFatAreaParam,
          tScore: tScoreParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ConfigOB] entity fields to define ObjectBox queries.
class ConfigOB_ {
  /// See [ConfigOB.id].
  static final id = obx.QueryIntegerProperty<ConfigOB>(
    _entities[0].properties[0],
  );

  /// See [ConfigOB.hasAcceptedDisclaimer].
  static final hasAcceptedDisclaimer = obx.QueryBooleanProperty<ConfigOB>(
    _entities[0].properties[1],
  );

  /// See [ConfigOB.hasAcceptedPolicy].
  static final hasAcceptedPolicy = obx.QueryBooleanProperty<ConfigOB>(
    _entities[0].properties[2],
  );

  /// See [ConfigOB.hasAcceptedSendAnonymousData].
  static final hasAcceptedSendAnonymousData =
      obx.QueryBooleanProperty<ConfigOB>(_entities[0].properties[3]);

  /// See [ConfigOB.selectedAppTheme].
  static final selectedAppTheme = obx.QueryIntegerProperty<ConfigOB>(
    _entities[0].properties[4],
  );

  /// See [ConfigOB.usesImperialUnits].
  static final usesImperialUnits = obx.QueryBooleanProperty<ConfigOB>(
    _entities[0].properties[5],
  );

  /// See [ConfigOB.userKcalAdjustment].
  static final userKcalAdjustment = obx.QueryDoubleProperty<ConfigOB>(
    _entities[0].properties[6],
  );

  /// See [ConfigOB.userCarbGoalPct].
  static final userCarbGoalPct = obx.QueryDoubleProperty<ConfigOB>(
    _entities[0].properties[7],
  );

  /// See [ConfigOB.userProteinGoalPct].
  static final userProteinGoalPct = obx.QueryDoubleProperty<ConfigOB>(
    _entities[0].properties[8],
  );

  /// See [ConfigOB.userFatGoalPct].
  static final userFatGoalPct = obx.QueryDoubleProperty<ConfigOB>(
    _entities[0].properties[9],
  );

  /// See [ConfigOB.hiveMigrationComplete].
  static final hiveMigrationComplete = obx.QueryBooleanProperty<ConfigOB>(
    _entities[0].properties[10],
  );

  /// See [ConfigOB.targetWeightKG].
  static final targetWeightKG = obx.QueryDoubleProperty<ConfigOB>(
    _entities[0].properties[11],
  );
}

/// [IntakeOB] entity fields to define ObjectBox queries.
class IntakeOB_ {
  /// See [IntakeOB.id].
  static final id = obx.QueryIntegerProperty<IntakeOB>(
    _entities[1].properties[0],
  );

  /// See [IntakeOB.intakeId].
  static final intakeId = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[1],
  );

  /// See [IntakeOB.unit].
  static final unit = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[2],
  );

  /// See [IntakeOB.amount].
  static final amount = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[3],
  );

  /// See [IntakeOB.intakeType].
  static final intakeType = obx.QueryIntegerProperty<IntakeOB>(
    _entities[1].properties[4],
  );

  /// See [IntakeOB.dateTime].
  static final dateTime = obx.QueryDateProperty<IntakeOB>(
    _entities[1].properties[5],
  );

  /// See [IntakeOB.code].
  static final code = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[6],
  );

  /// See [IntakeOB.name].
  static final name = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[7],
  );

  /// See [IntakeOB.brands].
  static final brands = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[8],
  );

  /// See [IntakeOB.thumbnailImageUrl].
  static final thumbnailImageUrl = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[9],
  );

  /// See [IntakeOB.mainImageUrl].
  static final mainImageUrl = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[10],
  );

  /// See [IntakeOB.url].
  static final url = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[11],
  );

  /// See [IntakeOB.mealQuantity].
  static final mealQuantity = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[12],
  );

  /// See [IntakeOB.mealUnit].
  static final mealUnit = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[13],
  );

  /// See [IntakeOB.servingQuantity].
  static final servingQuantity = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[14],
  );

  /// See [IntakeOB.servingUnit].
  static final servingUnit = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[15],
  );

  /// See [IntakeOB.servingSize].
  static final servingSize = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[16],
  );

  /// See [IntakeOB.mealSource].
  static final mealSource = obx.QueryIntegerProperty<IntakeOB>(
    _entities[1].properties[17],
  );

  /// See [IntakeOB.energyKcal100].
  static final energyKcal100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[18],
  );

  /// See [IntakeOB.carbohydrates100].
  static final carbohydrates100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[19],
  );

  /// See [IntakeOB.fat100].
  static final fat100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[20],
  );

  /// See [IntakeOB.proteins100].
  static final proteins100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[21],
  );

  /// See [IntakeOB.sugars100].
  static final sugars100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[22],
  );

  /// See [IntakeOB.saturatedFat100].
  static final saturatedFat100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[23],
  );

  /// See [IntakeOB.fiber100].
  static final fiber100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[24],
  );

  /// See [IntakeOB.sodium100].
  static final sodium100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[25],
  );

  /// See [IntakeOB.potassium100].
  static final potassium100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[26],
  );

  /// See [IntakeOB.calcium100].
  static final calcium100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[27],
  );

  /// See [IntakeOB.iron100].
  static final iron100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[28],
  );

  /// See [IntakeOB.magnesium100].
  static final magnesium100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[29],
  );

  /// See [IntakeOB.phosphorus100].
  static final phosphorus100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[30],
  );

  /// See [IntakeOB.zinc100].
  static final zinc100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[31],
  );

  /// See [IntakeOB.copper100].
  static final copper100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[32],
  );

  /// See [IntakeOB.manganese100].
  static final manganese100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[33],
  );

  /// See [IntakeOB.selenium100].
  static final selenium100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[34],
  );

  /// See [IntakeOB.vitaminA100].
  static final vitaminA100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[35],
  );

  /// See [IntakeOB.vitaminC100].
  static final vitaminC100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[36],
  );

  /// See [IntakeOB.vitaminD100].
  static final vitaminD100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[37],
  );

  /// See [IntakeOB.vitaminE100].
  static final vitaminE100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[38],
  );

  /// See [IntakeOB.vitaminK100].
  static final vitaminK100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[39],
  );

  /// See [IntakeOB.thiamine100].
  static final thiamine100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[40],
  );

  /// See [IntakeOB.riboflavin100].
  static final riboflavin100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[41],
  );

  /// See [IntakeOB.niacin100].
  static final niacin100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[42],
  );

  /// See [IntakeOB.pantothenicAcid100].
  static final pantothenicAcid100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[43],
  );

  /// See [IntakeOB.vitaminB6100].
  static final vitaminB6100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[44],
  );

  /// See [IntakeOB.folate100].
  static final folate100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[45],
  );

  /// See [IntakeOB.vitaminB12100].
  static final vitaminB12100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[46],
  );

  /// See [IntakeOB.cholesterol100].
  static final cholesterol100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[47],
  );

  /// See [IntakeOB.addedSugars100].
  static final addedSugars100 = obx.QueryDoubleProperty<IntakeOB>(
    _entities[1].properties[48],
  );

  /// See [IntakeOB.additivesTags].
  static final additivesTags = obx.QueryStringVectorProperty<IntakeOB>(
    _entities[1].properties[49],
  );

  /// See [IntakeOB.ingredientsText].
  static final ingredientsText = obx.QueryStringProperty<IntakeOB>(
    _entities[1].properties[50],
  );
}

/// [PhysicalActivityOB] entity fields to define ObjectBox queries.
class PhysicalActivityOB_ {
  /// See [PhysicalActivityOB.id].
  static final id = obx.QueryIntegerProperty<PhysicalActivityOB>(
    _entities[2].properties[0],
  );

  /// See [PhysicalActivityOB.code].
  static final code = obx.QueryStringProperty<PhysicalActivityOB>(
    _entities[2].properties[1],
  );

  /// See [PhysicalActivityOB.specificActivity].
  static final specificActivity = obx.QueryStringProperty<PhysicalActivityOB>(
    _entities[2].properties[2],
  );

  /// See [PhysicalActivityOB.description].
  static final description = obx.QueryStringProperty<PhysicalActivityOB>(
    _entities[2].properties[3],
  );

  /// See [PhysicalActivityOB.mets].
  static final mets = obx.QueryDoubleProperty<PhysicalActivityOB>(
    _entities[2].properties[4],
  );

  /// See [PhysicalActivityOB.tags].
  static final tags = obx.QueryStringVectorProperty<PhysicalActivityOB>(
    _entities[2].properties[5],
  );

  /// See [PhysicalActivityOB.activityType].
  static final activityType = obx.QueryIntegerProperty<PhysicalActivityOB>(
    _entities[2].properties[6],
  );
}

/// [TrackedDayOB] entity fields to define ObjectBox queries.
class TrackedDayOB_ {
  /// See [TrackedDayOB.id].
  static final id = obx.QueryIntegerProperty<TrackedDayOB>(
    _entities[3].properties[0],
  );

  /// See [TrackedDayOB.day].
  static final day = obx.QueryDateProperty<TrackedDayOB>(
    _entities[3].properties[1],
  );

  /// See [TrackedDayOB.calorieGoal].
  static final calorieGoal = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[2],
  );

  /// See [TrackedDayOB.caloriesTracked].
  static final caloriesTracked = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[3],
  );

  /// See [TrackedDayOB.carbsGoal].
  static final carbsGoal = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[4],
  );

  /// See [TrackedDayOB.carbsTracked].
  static final carbsTracked = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[5],
  );

  /// See [TrackedDayOB.fatGoal].
  static final fatGoal = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[6],
  );

  /// See [TrackedDayOB.fatTracked].
  static final fatTracked = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[7],
  );

  /// See [TrackedDayOB.proteinGoal].
  static final proteinGoal = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[8],
  );

  /// See [TrackedDayOB.proteinTracked].
  static final proteinTracked = obx.QueryDoubleProperty<TrackedDayOB>(
    _entities[3].properties[9],
  );
}

/// [UserActivityOB] entity fields to define ObjectBox queries.
class UserActivityOB_ {
  /// See [UserActivityOB.id].
  static final id = obx.QueryIntegerProperty<UserActivityOB>(
    _entities[4].properties[0],
  );

  /// See [UserActivityOB.activityId].
  static final activityId = obx.QueryStringProperty<UserActivityOB>(
    _entities[4].properties[1],
  );

  /// See [UserActivityOB.duration].
  static final duration = obx.QueryDoubleProperty<UserActivityOB>(
    _entities[4].properties[2],
  );

  /// See [UserActivityOB.burnedKcal].
  static final burnedKcal = obx.QueryDoubleProperty<UserActivityOB>(
    _entities[4].properties[3],
  );

  /// See [UserActivityOB.date].
  static final date = obx.QueryDateProperty<UserActivityOB>(
    _entities[4].properties[4],
  );

  /// See [UserActivityOB.activityCode].
  static final activityCode = obx.QueryStringProperty<UserActivityOB>(
    _entities[4].properties[5],
  );

  /// See [UserActivityOB.specificActivity].
  static final specificActivity = obx.QueryStringProperty<UserActivityOB>(
    _entities[4].properties[6],
  );

  /// See [UserActivityOB.description].
  static final description = obx.QueryStringProperty<UserActivityOB>(
    _entities[4].properties[7],
  );

  /// See [UserActivityOB.mets].
  static final mets = obx.QueryDoubleProperty<UserActivityOB>(
    _entities[4].properties[8],
  );

  /// See [UserActivityOB.tags].
  static final tags = obx.QueryStringVectorProperty<UserActivityOB>(
    _entities[4].properties[9],
  );

  /// See [UserActivityOB.activityType].
  static final activityType = obx.QueryIntegerProperty<UserActivityOB>(
    _entities[4].properties[10],
  );
}

/// [UserOB] entity fields to define ObjectBox queries.
class UserOB_ {
  /// See [UserOB.id].
  static final id = obx.QueryIntegerProperty<UserOB>(
    _entities[5].properties[0],
  );

  /// See [UserOB.birthday].
  static final birthday = obx.QueryDateProperty<UserOB>(
    _entities[5].properties[1],
  );

  /// See [UserOB.heightCM].
  static final heightCM = obx.QueryDoubleProperty<UserOB>(
    _entities[5].properties[2],
  );

  /// See [UserOB.weightKG].
  static final weightKG = obx.QueryDoubleProperty<UserOB>(
    _entities[5].properties[3],
  );

  /// See [UserOB.gender].
  static final gender = obx.QueryIntegerProperty<UserOB>(
    _entities[5].properties[4],
  );

  /// See [UserOB.goal].
  static final goal = obx.QueryIntegerProperty<UserOB>(
    _entities[5].properties[5],
  );

  /// See [UserOB.pal].
  static final pal = obx.QueryIntegerProperty<UserOB>(
    _entities[5].properties[6],
  );
}

/// [GutHealthItemOB] entity fields to define ObjectBox queries.
class GutHealthItemOB_ {
  /// See [GutHealthItemOB.id].
  static final id = obx.QueryIntegerProperty<GutHealthItemOB>(
    _entities[6].properties[0],
  );

  /// See [GutHealthItemOB.name].
  static final name = obx.QueryStringProperty<GutHealthItemOB>(
    _entities[6].properties[1],
  );

  /// See [GutHealthItemOB.category].
  static final category = obx.QueryStringProperty<GutHealthItemOB>(
    _entities[6].properties[2],
  );

  /// See [GutHealthItemOB.dateTime].
  static final dateTime = obx.QueryDateProperty<GutHealthItemOB>(
    _entities[6].properties[3],
  );

  /// See [GutHealthItemOB.isAutoFlagged].
  static final isAutoFlagged = obx.QueryBooleanProperty<GutHealthItemOB>(
    _entities[6].properties[4],
  );

  /// See [GutHealthItemOB.sourceIntakeId].
  static final sourceIntakeId = obx.QueryStringProperty<GutHealthItemOB>(
    _entities[6].properties[5],
  );
}

/// [HabitLogOB] entity fields to define ObjectBox queries.
class HabitLogOB_ {
  /// See [HabitLogOB.id].
  static final id = obx.QueryIntegerProperty<HabitLogOB>(
    _entities[7].properties[0],
  );

  /// See [HabitLogOB.habitId].
  static final habitId = obx.QueryIntegerProperty<HabitLogOB>(
    _entities[7].properties[1],
  );

  /// See [HabitLogOB.dateTime].
  static final dateTime = obx.QueryDateProperty<HabitLogOB>(
    _entities[7].properties[2],
  );

  /// See [HabitLogOB.completed].
  static final completed = obx.QueryBooleanProperty<HabitLogOB>(
    _entities[7].properties[3],
  );
}

/// [HabitOB] entity fields to define ObjectBox queries.
class HabitOB_ {
  /// See [HabitOB.id].
  static final id = obx.QueryIntegerProperty<HabitOB>(
    _entities[8].properties[0],
  );

  /// See [HabitOB.name].
  static final name = obx.QueryStringProperty<HabitOB>(
    _entities[8].properties[1],
  );

  /// See [HabitOB.category].
  static final category = obx.QueryStringProperty<HabitOB>(
    _entities[8].properties[2],
  );

  /// See [HabitOB.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<HabitOB>(
    _entities[8].properties[3],
  );

  /// See [HabitOB.isActive].
  static final isActive = obx.QueryBooleanProperty<HabitOB>(
    _entities[8].properties[4],
  );
}

/// [WaterRecordOB] entity fields to define ObjectBox queries.
class WaterRecordOB_ {
  /// See [WaterRecordOB.id].
  static final id = obx.QueryIntegerProperty<WaterRecordOB>(
    _entities[9].properties[0],
  );

  /// See [WaterRecordOB.amountML].
  static final amountML = obx.QueryDoubleProperty<WaterRecordOB>(
    _entities[9].properties[1],
  );

  /// See [WaterRecordOB.dateTime].
  static final dateTime = obx.QueryDateProperty<WaterRecordOB>(
    _entities[9].properties[2],
  );
}

/// [WeightRecordOB] entity fields to define ObjectBox queries.
class WeightRecordOB_ {
  /// See [WeightRecordOB.id].
  static final id = obx.QueryIntegerProperty<WeightRecordOB>(
    _entities[10].properties[0],
  );

  /// See [WeightRecordOB.weightKG].
  static final weightKG = obx.QueryDoubleProperty<WeightRecordOB>(
    _entities[10].properties[1],
  );

  /// See [WeightRecordOB.dateTime].
  static final dateTime = obx.QueryDateProperty<WeightRecordOB>(
    _entities[10].properties[2],
  );
}

/// [StoolLogOB] entity fields to define ObjectBox queries.
class StoolLogOB_ {
  /// See [StoolLogOB.id].
  static final id = obx.QueryIntegerProperty<StoolLogOB>(
    _entities[11].properties[0],
  );

  /// See [StoolLogOB.type].
  static final type = obx.QueryIntegerProperty<StoolLogOB>(
    _entities[11].properties[1],
  );

  /// See [StoolLogOB.dateTime].
  static final dateTime = obx.QueryDateProperty<StoolLogOB>(
    _entities[11].properties[2],
  );

  /// See [StoolLogOB.notes].
  static final notes = obx.QueryStringProperty<StoolLogOB>(
    _entities[11].properties[3],
  );
}

/// [SymptomLogOB] entity fields to define ObjectBox queries.
class SymptomLogOB_ {
  /// See [SymptomLogOB.id].
  static final id = obx.QueryIntegerProperty<SymptomLogOB>(
    _entities[12].properties[0],
  );

  /// See [SymptomLogOB.symptom].
  static final symptom = obx.QueryIntegerProperty<SymptomLogOB>(
    _entities[12].properties[1],
  );

  /// See [SymptomLogOB.severity].
  static final severity = obx.QueryIntegerProperty<SymptomLogOB>(
    _entities[12].properties[2],
  );

  /// See [SymptomLogOB.dateTime].
  static final dateTime = obx.QueryDateProperty<SymptomLogOB>(
    _entities[12].properties[3],
  );

  /// See [SymptomLogOB.notes].
  static final notes = obx.QueryStringProperty<SymptomLogOB>(
    _entities[12].properties[4],
  );
}

/// [BiomarkerRecordOB] entity fields to define ObjectBox queries.
class BiomarkerRecordOB_ {
  /// See [BiomarkerRecordOB.id].
  static final id = obx.QueryIntegerProperty<BiomarkerRecordOB>(
    _entities[13].properties[0],
  );

  /// See [BiomarkerRecordOB.type].
  static final type = obx.QueryStringProperty<BiomarkerRecordOB>(
    _entities[13].properties[1],
  );

  /// See [BiomarkerRecordOB.value].
  static final value = obx.QueryDoubleProperty<BiomarkerRecordOB>(
    _entities[13].properties[2],
  );

  /// See [BiomarkerRecordOB.unit].
  static final unit = obx.QueryStringProperty<BiomarkerRecordOB>(
    _entities[13].properties[3],
  );

  /// See [BiomarkerRecordOB.dateTime].
  static final dateTime = obx.QueryDateProperty<BiomarkerRecordOB>(
    _entities[13].properties[4],
  );

  /// See [BiomarkerRecordOB.source].
  static final source = obx.QueryIntegerProperty<BiomarkerRecordOB>(
    _entities[13].properties[5],
  );
}

/// [DexaScanOB] entity fields to define ObjectBox queries.
class DexaScanOB_ {
  /// See [DexaScanOB.id].
  static final id = obx.QueryIntegerProperty<DexaScanOB>(
    _entities[14].properties[0],
  );

  /// See [DexaScanOB.scanDate].
  static final scanDate = obx.QueryDateProperty<DexaScanOB>(
    _entities[14].properties[1],
  );

  /// See [DexaScanOB.totalBodyFatPercent].
  static final totalBodyFatPercent = obx.QueryDoubleProperty<DexaScanOB>(
    _entities[14].properties[2],
  );

  /// See [DexaScanOB.leanMassKG].
  static final leanMassKG = obx.QueryDoubleProperty<DexaScanOB>(
    _entities[14].properties[3],
  );

  /// See [DexaScanOB.fatMassKG].
  static final fatMassKG = obx.QueryDoubleProperty<DexaScanOB>(
    _entities[14].properties[4],
  );

  /// See [DexaScanOB.boneMineralDensity].
  static final boneMineralDensity = obx.QueryDoubleProperty<DexaScanOB>(
    _entities[14].properties[5],
  );

  /// See [DexaScanOB.visceralFatArea].
  static final visceralFatArea = obx.QueryDoubleProperty<DexaScanOB>(
    _entities[14].properties[6],
  );

  /// See [DexaScanOB.tScore].
  static final tScore = obx.QueryDoubleProperty<DexaScanOB>(
    _entities[14].properties[7],
  );
}
